### ISSUE TITLE
reported error

### ISSUE THREAD

**Issue by meitiever** [jetsonhacks/installLibrealsenseTX1#1]
Hi jetson hackers
    I followed the steps of your youtube videos install ssd and librealsense.
    I have two problems after the installation. could you help me fix it please.
    1. after i set up sata ssd, and reboot the os. the screen stopped at Freeing alternatives memory 52k(xxxxxx-xxxxxxx), i have to reset the computer and then os come back. boot up from internal eMMC is ok. -- this is not important.
    2. after the steps of librealsense, connect realsense before boot up, but the uvc module is not loaded. 
command lsmod shows no uvc driver. and cpp-config-ui throw uvcvideo kernel module is not loaded.
reported Failed to set UVC commit control when boot up.

all the installation steps are prefect and no error reported.

thanks
Steve

**Comment by meitiever** [comment]
all the steps are prefect and no error reported.
thanks

**Comment by jetsonhacks** [comment]
You haven't given enough information to help. Did you follow the article at: http://www.jetsonhacks.com/2016/10/06/intel-realsense-camera-installation-nvidia-jetson-tx1/
When did you rebuild the kernel?
What is the result of: 
$ uname -a
Did you rebuild the kernel on the current root device (SSD or eMMC)?

**Comment by meitiever** [comment]
A new version of l4t will be released tomorrow, if i re-flash OS with this release(kernel version 4.4). must i  rebuild the kernel again?

thanks
steve

**Comment by jetsonhacks** [comment]
If you have a Jetson TX2, then the kernel version is 4.4. This will require a different procedure for installing librealsense than the earlier TX1. Under the new release, there is no change to the Jetson TX1 BSP and kernel which remain at L4T 24.2.1 and 3.10.96.

**Comment by jetsonhacks** [comment]
If you have a Jetson TX2, then the kernel version is 4.4. This will require a different procedure for installing librealsense than the earlier TX1. Under the new release, there is no change to the Jetson TX1 BSP and kernel which remain at L4T 24.2.1 and 3.10.96.
