### ISSUE TITLE
No uvcvideo module loaded at boot

### ISSUE THREAD

**Issue by richrdcm** [jetsonhacks/installLibrealsenseTX1#3]
Hi, I install the library on my jetson tx1, almost everything turnout well but the qt installation from the trusty repositories, I managed to install qt anyway and the library compiled but at restart the uvcvideo is not loaded, therefore when I run a builded example from the library it says no camera is detected.

**My specs:**
Kernel: 4.4.38-jetsonbot-v0.2
Camera model: sr300
Operating System & Version: Ubuntu 16.04 (Linux for Tegra 28.1)

**My installation went like follows:**
`You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 7332eca... Bump version
patching file src/uvc-v4l2.cpp
Hit:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
Ign:2 http://archive.ubuntu.com/ubuntu trusty InRelease                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease                                      
Hit:5 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease                                     
Get:4 http://archive.ubuntu.com/ubuntu trusty Release [58.5 kB]                    
Get:6 http://archive.ubuntu.com/ubuntu trusty Release.gpg [933 B]                            
Hit:7 http://packages.ros.org/ros/ubuntu xenial InRelease                                     
Ign:8 http://archive.ubuntu.com/ubuntu trusty/main arm64 Packages
Ign:9 http://archive.ubuntu.com/ubuntu trusty/universe arm64 Packages
Ign:8 http://archive.ubuntu.com/ubuntu trusty/main arm64 Packages
Ign:9 http://archive.ubuntu.com/ubuntu trusty/universe arm64 Packages
Err:8 http://archive.ubuntu.com/ubuntu trusty/main arm64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Ign:9 http://archive.ubuntu.com/ubuntu trusty/universe arm64 Packages
Fetched 59.4 kB in 0s (71.7 kB/s)
Reading package lists... Done
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/main/binary-arm64/Packages  404  Not Found [IP: 91.189.88.149 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
-- Info: REALSENSE_VERSION_STRING=1.12.1
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Checking for one of the modules 'libusb-1.0'
-- Found OpenGL: /usr/lib/aarch64-linux-gnu/libGL.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nvidia/librealsense/build
Scanning dependencies of target realsense
[  1%] Building CXX object CMakeFiles/realsense.dir/src/archive.cpp.o
[  2%] Building CXX object CMakeFiles/realsense.dir/src/context.cpp.o
[  3%] Building CXX object CMakeFiles/realsense.dir/src/device.cpp.o
[  4%] Building CXX object CMakeFiles/realsense.dir/src/ds-device.cpp.o
[  5%] Building CXX object CMakeFiles/realsense.dir/src/ds-private.cpp.o
[  6%] Building CXX object CMakeFiles/realsense.dir/src/f200.cpp.o
[  7%] Building CXX object CMakeFiles/realsense.dir/src/hw-monitor.cpp.o
[  9%] Building CXX object CMakeFiles/realsense.dir/src/image.cpp.o
[ 10%] Building CXX object CMakeFiles/realsense.dir/src/ivcam-private.cpp.o
[ 11%] Building CXX object CMakeFiles/realsense.dir/src/ivcam-device.cpp.o
[ 12%] Building CXX object CMakeFiles/realsense.dir/src/log.cpp.o
[ 13%] Building CXX object CMakeFiles/realsense.dir/src/motion-module.cpp.o
[ 14%] Building CXX object CMakeFiles/realsense.dir/src/r200.cpp.o
[ 15%] Building CXX object CMakeFiles/realsense.dir/src/rs.cpp.o
[ 17%] Building CXX object CMakeFiles/realsense.dir/src/sr300.cpp.o
[ 18%] Building CXX object CMakeFiles/realsense.dir/src/stream.cpp.o
[ 19%] Building CXX object CMakeFiles/realsense.dir/src/sync.cpp.o
[ 20%] Building CXX object CMakeFiles/realsense.dir/src/timestamps.cpp.o
[ 21%] Building CXX object CMakeFiles/realsense.dir/src/types.cpp.o
[ 22%] Building CXX object CMakeFiles/realsense.dir/src/uvc-libuvc.cpp.o
[ 23%] Building CXX object CMakeFiles/realsense.dir/src/uvc-v4l2.cpp.o
[ 25%] Building CXX object CMakeFiles/realsense.dir/src/uvc-wmf.cpp.o
[ 26%] Building CXX object CMakeFiles/realsense.dir/src/uvc.cpp.o
[ 27%] Building C object CMakeFiles/realsense.dir/src/verify.c.o
[ 28%] Building CXX object CMakeFiles/realsense.dir/src/zr300.cpp.o
[ 29%] Building C object CMakeFiles/realsense.dir/src/libuvc/ctrl.c.o
[ 30%] Building C object CMakeFiles/realsense.dir/src/libuvc/dev.c.o
[ 31%] Building C object CMakeFiles/realsense.dir/src/libuvc/diag.c.o
[ 32%] Building C object CMakeFiles/realsense.dir/src/libuvc/frame.c.o
[ 34%] Building C object CMakeFiles/realsense.dir/src/libuvc/init.c.o
[ 35%] Building C object CMakeFiles/realsense.dir/src/libuvc/stream.c.o
[ 36%] Linking CXX shared library librealsense.so
[ 36%] Built target realsense
Scanning dependencies of target cpp-capture
[ 37%] Building CXX object examples/CMakeFiles/cpp-capture.dir/cpp-capture.cpp.o
[ 38%] Linking CXX executable cpp-capture
[ 38%] Built target cpp-capture
Scanning dependencies of target cpp-enumerate-devices
[ 39%] Building CXX object examples/CMakeFiles/cpp-enumerate-devices.dir/cpp-enumerate-devices.cpp.o
[ 40%] Linking CXX executable cpp-enumerate-devices
[ 40%] Built target cpp-enumerate-devices
Scanning dependencies of target cpp-pointcloud
[ 42%] Building CXX object examples/CMakeFiles/cpp-pointcloud.dir/cpp-pointcloud.cpp.o
[ 43%] Linking CXX executable cpp-pointcloud
[ 43%] Built target cpp-pointcloud
Scanning dependencies of target cpp-tutorial-3-pointcloud
[ 44%] Building CXX object examples/CMakeFiles/cpp-tutorial-3-pointcloud.dir/cpp-tutorial-3-pointcloud.cpp.o
[ 45%] Linking CXX executable cpp-tutorial-3-pointcloud
[ 45%] Built target cpp-tutorial-3-pointcloud
Scanning dependencies of target c-tutorial-3-pointcloud
[ 46%] Building C object examples/CMakeFiles/c-tutorial-3-pointcloud.dir/c-tutorial-3-pointcloud.c.o
[ 47%] Linking C executable c-tutorial-3-pointcloud
[ 47%] Built target c-tutorial-3-pointcloud
Scanning dependencies of target cpp-alignimages
[ 48%] Building CXX object examples/CMakeFiles/cpp-alignimages.dir/cpp-alignimages.cpp.o
[ 50%] Linking CXX executable cpp-alignimages
[ 50%] Built target cpp-alignimages
Scanning dependencies of target c-tutorial-1-depth
[ 51%] Building C object examples/CMakeFiles/c-tutorial-1-depth.dir/c-tutorial-1-depth.c.o
[ 52%] Linking C executable c-tutorial-1-depth
[ 52%] Built target c-tutorial-1-depth
Scanning dependencies of target cpp-callback-2
[ 53%] Building CXX object examples/CMakeFiles/cpp-callback-2.dir/cpp-callback-2.cpp.o
[ 54%] Linking CXX executable cpp-callback-2
[ 54%] Built target cpp-callback-2
Scanning dependencies of target c-tutorial-2-streams
[ 55%] Building C object examples/CMakeFiles/c-tutorial-2-streams.dir/c-tutorial-2-streams.c.o
[ 56%] Linking C executable c-tutorial-2-streams
[ 56%] Built target c-tutorial-2-streams
Scanning dependencies of target cpp-stride
[ 57%] Building CXX object examples/CMakeFiles/cpp-stride.dir/cpp-stride.cpp.o
[ 59%] Linking CXX executable cpp-stride
[ 59%] Built target cpp-stride
Scanning dependencies of target cpp-tutorial-2-streams
[ 60%] Building CXX object examples/CMakeFiles/cpp-tutorial-2-streams.dir/cpp-tutorial-2-streams.cpp.o
[ 61%] Linking CXX executable cpp-tutorial-2-streams
[ 61%] Built target cpp-tutorial-2-streams
Scanning dependencies of target cpp-tutorial-1-depth
[ 62%] Building CXX object examples/CMakeFiles/cpp-tutorial-1-depth.dir/cpp-tutorial-1-depth.cpp.o
[ 63%] Linking CXX executable cpp-tutorial-1-depth
[ 63%] Built target cpp-tutorial-1-depth
Scanning dependencies of target cpp-config-ui
[ 64%] Building CXX object examples/CMakeFiles/cpp-config-ui.dir/cpp-config-ui.cpp.o
[ 65%] Linking CXX executable cpp-config-ui
[ 65%] Built target cpp-config-ui
Scanning dependencies of target cpp-headless
[ 67%] Building CXX object examples/CMakeFiles/cpp-headless.dir/cpp-headless.cpp.o
[ 68%] Linking CXX executable cpp-headless
[ 68%] Built target cpp-headless
Scanning dependencies of target cpp-callback
[ 69%] Building CXX object examples/CMakeFiles/cpp-callback.dir/cpp-callback.cpp.o
[ 70%] Linking CXX executable cpp-callback
[ 70%] Built target cpp-callback
Scanning dependencies of target cpp-motion-module
[ 71%] Building CXX object examples/CMakeFiles/cpp-motion-module.dir/cpp-motion-module.cpp.o
[ 72%] Linking CXX executable cpp-motion-module
[ 72%] Built target cpp-motion-module
Scanning dependencies of target cpp-restart
[ 73%] Building CXX object examples/CMakeFiles/cpp-restart.dir/cpp-restart.cpp.o
[ 75%] Linking CXX executable cpp-restart
[ 75%] Built target cpp-restart
Scanning dependencies of target cpp-multicam
[ 76%] Building CXX object examples/CMakeFiles/cpp-multicam.dir/cpp-multicam.cpp.o
[ 77%] Linking CXX executable cpp-multicam
[ 77%] Built target cpp-multicam
Scanning dependencies of target SR300-live-test
[ 78%] Building CXX object unit-tests/CMakeFiles/SR300-live-test.dir/unit-tests-live.cpp.o
[ 79%] Building CXX object unit-tests/CMakeFiles/SR300-live-test.dir/unit-tests-live-sr300.cpp.o
[ 80%] Linking CXX executable SR300-live-test
[ 80%] Built target SR300-live-test
Scanning dependencies of target R200-live-test
[ 81%] Building CXX object unit-tests/CMakeFiles/R200-live-test.dir/unit-tests-live.cpp.o
[ 82%] Building CXX object unit-tests/CMakeFiles/R200-live-test.dir/unit-tests-live-ds-common.cpp.o
[ 84%] Building CXX object unit-tests/CMakeFiles/R200-live-test.dir/unit-tests-live-r200.cpp.o
[ 85%] Linking CXX executable R200-live-test
[ 85%] Built target R200-live-test
Scanning dependencies of target F200-live-test
[ 86%] Building CXX object unit-tests/CMakeFiles/F200-live-test.dir/unit-tests-live.cpp.o
[ 87%] Building CXX object unit-tests/CMakeFiles/F200-live-test.dir/unit-tests-live-f200.cpp.o
[ 88%] Linking CXX executable F200-live-test
[ 88%] Built target F200-live-test
Scanning dependencies of target ZR300-live-test
[ 89%] Building CXX object unit-tests/CMakeFiles/ZR300-live-test.dir/unit-tests-live.cpp.o
[ 90%] Building CXX object unit-tests/CMakeFiles/ZR300-live-test.dir/unit-tests-live-ds-common.cpp.o
[ 92%] Building CXX object unit-tests/CMakeFiles/ZR300-live-test.dir/unit-tests-live-zr300.cpp.o
[ 93%] Linking CXX executable ZR300-live-test
[ 93%] Built target ZR300-live-test
Scanning dependencies of target offline-test
[ 94%] Building CXX object unit-tests/CMakeFiles/offline-test.dir/unit-tests-offline.cpp.o
[ 95%] Linking CXX executable offline-test
[ 95%] Built target offline-test
Scanning dependencies of target LR200-live-test
[ 96%] Building CXX object unit-tests/CMakeFiles/LR200-live-test.dir/unit-tests-live.cpp.o
[ 97%] Building CXX object unit-tests/CMakeFiles/LR200-live-test.dir/unit-tests-live-ds-common.cpp.o
[ 98%] Building CXX object unit-tests/CMakeFiles/LR200-live-test.dir/unit-tests-live-lr200.cpp.o
[100%] Linking CXX executable LR200-live-test
[100%] Built target LR200-live-test
[ 36%] Built target realsense
[ 38%] Built target cpp-capture
[ 40%] Built target cpp-enumerate-devices
[ 43%] Built target cpp-pointcloud
[ 45%] Built target cpp-tutorial-3-pointcloud
[ 47%] Built target c-tutorial-3-pointcloud
[ 50%] Built target cpp-alignimages
[ 52%] Built target c-tutorial-1-depth
[ 54%] Built target cpp-callback-2
[ 56%] Built target c-tutorial-2-streams
[ 59%] Built target cpp-stride
[ 61%] Built target cpp-tutorial-2-streams
[ 63%] Built target cpp-tutorial-1-depth
[ 65%] Built target cpp-config-ui
[ 68%] Built target cpp-headless
[ 70%] Built target cpp-callback
[ 72%] Built target cpp-motion-module
[ 75%] Built target cpp-restart
[ 77%] Built target cpp-multicam
[ 80%] Built target SR300-live-test
[ 85%] Built target R200-live-test
[ 88%] Built target F200-live-test
[ 93%] Built target ZR300-live-test
[ 95%] Built target offline-test
[100%] Built target LR200-live-test
Install the project...[ 4665.177906] usb 1-3.1: new high-speed USB device number 5 using xhci-tegra
[ 4665.201105] usb 1-3.1: New USB device found, idVendor=05e3, idProduct=0610
[ 4665.208011] usb 1-3.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4665.215614] usb 1-3.1: Product: USB2.0 Hub
[ 4665.219795] usb 1-3.1: Manufacturer: GenesysLogic
[ 4665.226986] hub 1-3.1:1.0: USB hub found
[ 4665.233103] hub 1-3.1:1.0: 2 ports detected
[ 4666.442082] usb 1-3.1.2: new full-speed USB device number 6 using xhci-tegra
[ 4666.563638] usb 1-3.1.2: config 1 has an invalid interface number: 3 but max is 2
[ 4666.571578] usb 1-3.1.2: config 1 has no interface number 2
[ 4666.652361] usb 1-3.1.2: New USB device found, idVendor=041e, idProduct=409b
[ 4666.659676] usb 1-3.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4666.668871] usb 1-3.1.2: Product: BlasterX Senz3D VF0810
[ 4666.674961] usb 1-3.1.2: Manufacturer: Creative Technology Ltd
[ 4666.681494] usb 1-3.1.2: SerialNumber: 170424125225
[ 4666.789400] input: Creative Technology Ltd BlasterX Senz3D VF0810 as /devices/70090000.xusb/usb1/1-3/1-3.1/1-3.1.2/1-3.1.2:1.3/0003:041E:409B.0003/input/input5
[ 4666.874843] hid-generic 0003:041E:409B.0003: input,hiddev0,hidraw2: USB HID v1.11 Device [Creative Technology Ltd BlasterX Senz3D VF0810] on usb-70090000.xusb-3.1.2/input3
-- Install configuration: ""
-- Installing: /usr/local/lib/librealsense.so.1.12.1
-- Up-to-date: /usr/local/lib/librealsense.so.1
-- Up-to-date: /usr/local/lib/librealsense.so
-- Up-to-date: /usr/local/include/librealsense
-- Installing: /usr/local/include/librealsense/rs.h
-- Installing: /usr/local/include/librealsense/rs.hpp
-- Installing: /usr/local/include/librealsense/rsutil.h
-- Installing: /usr/local/include/librealsense/rscore.hpp
-- Installing: /usr/local/bin/c-tutorial-1-depth
-- Set runtime path of "/usr/local/bin/c-tutorial-1-depth" to ""
-- Installing: /usr/local/bin/c-tutorial-2-streams
-- Set runtime path of "/usr/local/bin/c-tutorial-2-streams" to ""
-- Installing: /usr/local/bin/c-tutorial-3-pointcloud
-- Set runtime path of "/usr/local/bin/c-tutorial-3-pointcloud" to ""
-- Installing: /usr/local/bin/cpp-tutorial-1-depth
-- Set runtime path of "/usr/local/bin/cpp-tutorial-1-depth" to ""
-- Installing: /usr/local/bin/cpp-tutorial-2-streams
-- Set runtime path of "/usr/local/bin/cpp-tutorial-2-streams" to ""
-- Installing: /usr/local/bin/cpp-tutorial-3-pointcloud
-- Set runtime path of "/usr/local/bin/cpp-tutorial-3-pointcloud" to ""
-- Installing: /usr/local/bin/cpp-alignimages
-- Set runtime path of "/usr/local/bin/cpp-alignimages" to ""
-- Installing: /usr/local/bin/cpp-callback
-- Set runtime path of "/usr/local/bin/cpp-callback" to ""
-- Installing: /usr/local/bin/cpp-callback-2
-- Set runtime path of "/usr/local/bin/cpp-callback-2" to ""
-- Installing: /usr/local/bin/cpp-capture
-- Set runtime path of "/usr/local/bin/cpp-capture" to ""
-- Installing: /usr/local/bin/cpp-config-ui
-- Set runtime path of "/usr/local/bin/cpp-config-ui" to ""
-- Installing: /usr/local/bin/cpp-enumerate-devices
-- Set runtime path of "/usr/local/bin/cpp-enumerate-devices" to ""
-- Installing: /usr/local/bin/cpp-headless
-- Set runtime path of "/usr/local/bin/cpp-headless" to ""
-- Installing: /usr/local/bin/cpp-motion-module
-- Set runtime path of "/usr/local/bin/cpp-motion-module" to ""
-- Installing: /usr/local/bin/cpp-multicam
-- Set runtime path of "/usr/local/bin/cpp-multicam" to ""
-- Installing: /usr/local/bin/cpp-pointcloud
-- Set runtime path of "/usr/local/bin/cpp-pointcloud" to ""
-- Installing: /usr/local/bin/cpp-restart
-- Set runtime path of "/usr/local/bin/cpp-restart" to ""
-- Installing: /usr/local/bin/cpp-stride
-- Set runtime path of "/usr/local/bin/cpp-stride" to ""`

**My dmesg when I plug the camera:**
[ 4665.177906] usb 1-3.1: new high-speed USB device number 5 using xhci-tegra
[ 4665.201105] usb 1-3.1: New USB device found, idVendor=05e3, idProduct=0610
[ 4665.208011] usb 1-3.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4665.215614] usb 1-3.1: Product: USB2.0 Hub
[ 4665.219795] usb 1-3.1: Manufacturer: GenesysLogic
[ 4665.226986] hub 1-3.1:1.0: USB hub found
[ 4665.233103] hub 1-3.1:1.0: 2 ports detected
[ 4666.442082] usb 1-3.1.2: new full-speed USB device number 6 using xhci-tegra
[ 4666.563638] usb 1-3.1.2: config 1 has an invalid interface number: 3 but max is 2
[ 4666.571578] usb 1-3.1.2: config 1 has no interface number 2
[ 4666.652361] usb 1-3.1.2: New USB device found, idVendor=041e, idProduct=409b
[ 4666.659676] usb 1-3.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4666.668871] usb 1-3.1.2: Product: BlasterX Senz3D VF0810
[ 4666.674961] usb 1-3.1.2: Manufacturer: Creative Technology Ltd
[ 4666.681494] usb 1-3.1.2: SerialNumber: 170424125225
[ 4666.789400] input: Creative Technology Ltd BlasterX Senz3D VF0810 as /devices/70090000.xusb/usb1/1-3/1-3.1/1-3.1.2/1-3.1.2:1.3/0003:041E:409B.0003/input/input5
[ 4666.874843] hid-generic 0003:041E:409B.0003: input,hiddev0,hidraw2: USB HID v1.11 Device [Creative Technology Ltd BlasterX Senz3D VF0810] on usb-70090000.xusb-3.1.2/input3

**uvcvideo module is not on the file /etc/modules-load.d/modules.conf**

Thanks for any help

**Comment by jetsonhacks** [comment]
It appears as if you are using a USB 2.0 hub. The RealSense requires USB 3.0 or else uvcvideo does not recognize if.

**Comment by richrdcm** [comment]
Thank you to answer so fast, that was the mistake, it works like a charm.
