### ISSUE TITLE
uvcvideo: unknown video format

### ISSUE THREAD

**Issue by rishisoni10** [jetsonhacks/installLibrealsenseTX1#4]
I am using a TX1, and I have followed the instructions for L4T 28.1. I built the kernel from the TX1 tutorial and installed the librealsense library. However, after running ./cpp-config-ui, an error message saying "No device found. Is it plugged in?" is displayed. The following is the system information:

$ uname -r 
4.4.38-jetsonbot-v0.1

$ uname -a
Linux tegra-ubuntu 4.4.38-jetsonbot-v0.1 #1 SMP PREEMPT Mon Mar 5 20:19:05 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

Version of installLibrealsenseTX1: current master branch (L4T 28.1)
$ dmesg | tail -n 50

[ 1638.567980] usb 2-2.2: new SuperSpeed USB device number 5 using xhci-tegra
[ 1638.593524] usb 2-2.2: New USB device found, idVendor=8086, idProduct=0ad4
[ 1638.600439] usb 2-2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1638.607806] usb 2-2.2: Product: Intel(R) RealSense(TM) 430
[ 1638.613296] usb 2-2.2: Manufacturer: Intel(R) RealSense(TM) 430
[ 1638.619215] usb 2-2.2: SerialNumber: 748613020049
[ 1638.625658] uvcvideo: Unknown video format 00000050-0000-0010-8000-00aa00389b71
[ 1638.633034] uvcvideo: Unknown video format 00000032-0000-0010-8000-00aa00389b71
[ 1638.640708] uvcvideo: Found UVC 1.50 device Intel(R) RealSense(TM) 430 (8086:0ad4)
[ 1638.653257] uvcvideo: Unable to create debugfs 2-5 directory.
[ 1638.659211] input: Intel(R) RealSense(TM) 430 as /devices/70090000.xusb/usb2/2-2/2-2.2/2-2.2:1.0/input/input4

$ lsmod
Module                    Size          Used by
bcmdhd               7668673          0
bluedroid_pm           13770         0

I have even tried a powered USB 3.0 hub with no avail. Any help would be appreciated

**Comment by jetsonhacks** [comment]
You are attempting to run librealsense version 1.x with a D430 series camera. The new D430 requires librealsense 2.X.

**Comment by rishisoni10** [comment]
Yes that could have been the mistake. Now that I am trying to install v2.10.1 (I changed the git checkout in installLibrealsenseTX1.sh to 2.10.1), I get a prompt on the terminal that the patch script cannot find the particular file to be patched. The following is the terminal output right before the patch prompt:

Note: checking out 'v2.10.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new-branch-name

HEAD is now at 3e2e483... Merge pull request #1260 from IntelRealSense/master
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
/---------------------------
|diff --git a/src/uvc-v4l2.cpp b/src/uvc-v4l2.cpp
|index e97dfda..13f0596 100644
|--- a/src/uvc-v4l2.cpp
|+++ b/src/uvc-v4l2.cpp
/--------------------------
File to patch: 


Is there a different file to be patched for v2.x? Or does this version of realsense requires no patches?

**Comment by jetsonhacks** [comment]
This repository is for librealsense 1.X. This repository does not support librealsense 2.X. Librealsense 2.x requires a different set of kernel patches and module builds. Please refer to the librealsense documentation on their Github account.
